version: "3"

services:
  app:
    container_name: app
    image: mradib/nginx-php7.4-phalcon4.0.5
    restart: on-failure
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    expose:
      - "8080"
    environment:
      TZ: ${TIMEZONE}
      EXCHANGERATES_API_KEY: ${EXCHANGERATES_API_KEY}
      MrAdib: True
